Add instance for OsString
haskell-unordered-containers/hashable pull request #262
Opened 2022-11-21 22:33 UTC by tbidne

Resolves #254.

Since `OsPath` is a [type synonym](https://hackage.haskell.org/package/filepath-1.4.100.0/docs/System-OsPath.html#t:OsPath) for `OsString`, and `OsString` is a [`ShortByteString`](https://hackage.haskell.org/package/filepath-1.4.100.0/docs/System-OsString-Internal-Types.html#t:OsString), the most straightforward way to add the instance seems to be to reuse the `ShortByteString` instance.

A few thoughts:

1. CPP could be added to control the new dependency. I chose not to do this but am fine with whatever the maintainers think.
2. Is there a better way to do this?

    ```haskell
    instance Hashable OsString where
        hashWithSalt salt = hashWithSalt salt . getSBS . getOsString
          where
    #if defined(mingw32_HOST_OS) || defined(__MINGW32__)
            getSBS = getWindowsString
    #else
            getSBS = getPosixString
    #endif
    ```
    
    I was surprised that I could not find a `OsString -> ShortByteString` function, even in an internal module (is there one?), though maybe exposing that would be antithetical to AFP's goals.
3. I bumped the minor version since it is just adding a new instance, but perhaps it warrants a major bump due to the new dependencies (e.g. `filepath`, transitive `exceptions`). I'm not sure what [PVP](https://pvp.haskell.org/) has to say on this.

2022-11-21 22:48 UTC, phadej requested changes
- The 1. is no go. `filepath` lower bound has to stay at what it is. Forcing people to upgrade `filepath` is bad. (EDIT: they might want newer `hashable` for other reasons than these instances; upgrading `filepath` is often impossible or hard as [`ghc`](https://hackage.haskell.org/package/ghc) depends on it).
- For *2. Is there a better way to do this?* Add instances for `PosixString` and `WindowString`. I'd require these anyway.

2022-11-22 02:34 UTC, tbidne commented
1. Makes sense. What should the bound be since `filepath` is a new dep? Hashable's `base` lower bound is currently 4.5 (GHC 7.4.1), which corresponds to `filepath` 1.3.0.0, according to the version [matrix](https://gitlab.haskell.org/ghc/ghc/-/wikis/commentary/libraries/version-history).

2022-11-22 03:03 UTC, tbidne commented
I went ahead and changed 2, and relaxed the `filepath` lower bound to 1.3.0.0 FYI.

2022-11-22 08:55 UTC, phadej commented
If CI fails please don't repush. I want to see why it failed.

2022-11-23 00:37 UTC, tbidne commented
Understood. That said, I took the liberty of pushing once more, as I figured out what the CI failures were about: I needed to add the `filepath` dependency to `hashable-bench.cabal` as well. CI passed on my fork, so hopefully it does here as well.

2022-12-01 22:10 UTC, tbidne commented
@phadej do you have any more requests?

2023-01-05 15:14 UTC, closed without merging

2023-01-07 00:58 UTC, tbidne commented
Thank you!